import { observeWorkers } from "./workers-service.js";
import { escapeHtml, examStatus, workerDocumentSummary } from "./worker-utils.js";
let workers=[];let started=false;let refresh=null;let query="";let filter="all";
function rows(){
  return workers.flatMap(worker=>workerDocumentSummary(worker).items.map(item=>({worker,item,status:examStatus(item.vencimiento)})));
}
function renderRows(){
  const root=document.getElementById("documentsRows");if(!root)return;const q=query.trim().toLowerCase();
  const filtered=rows().filter(row=>(filter==="all"||row.status.code===filter)&&(!q||[row.worker.nombre,row.item.nombre,row.item.categoria,row.item.archivoNombre].some(value=>String(value||"").toLowerCase().includes(q))));
  root.innerHTML=filtered.length?filtered.map(row=>`<tr><td><strong>${escapeHtml(row.worker.nombre)}</strong><div class="table-sub">${escapeHtml(row.worker.rut||"")}</div></td><td>${escapeHtml(row.item.categoria)}</td><td>${escapeHtml(row.item.nombre)}</td><td>${escapeHtml(row.item.fecha||"—")}</td><td>${escapeHtml(row.item.vencimiento||"—")}</td><td><span class="status-pill ${row.status.className}">${row.status.label}</span></td><td>${row.item.archivoNombre?escapeHtml(row.item.archivoNombre):'<span class="table-sub">Sin archivo</span>'}</td></tr>`).join(""):`<tr><td colspan="7" class="empty">No hay documentos que coincidan.</td></tr>`;
}
export function initDocumentsModule(onChange){refresh=onChange;if(started)return;started=true;observeWorkers(data=>{workers=data;if(refresh)refresh();});}
export function renderDocuments(){const all=rows();const expired=all.filter(row=>row.status.code==="vencido").length;const warning=all.filter(row=>row.status.code==="por_vencer").length;const valid=all.filter(row=>row.status.code==="vigente").length;return `<section class="module-header"><div><h2>Documentos y exámenes</h2><p>Vista transversal de exámenes fijos, documentos adicionales y certificaciones.</p></div></section><section class="kpi-grid worker-kpis"><article class="kpi-card"><div class="kpi-value">${all.length}</div><div class="kpi-label">Registros</div></article><article class="kpi-card success"><div class="kpi-value">${valid}</div><div class="kpi-label">Vigentes</div></article><article class="kpi-card warning"><div class="kpi-value">${warning}</div><div class="kpi-label">Por vencer</div></article><article class="kpi-card danger"><div class="kpi-value">${expired}</div><div class="kpi-label">Vencidos</div></article></section><section class="workers-toolbar"><div class="search-control"><span>🔎</span><input id="documentsSearch" value="${escapeHtml(query)}" placeholder="Buscar trabajador o documento"></div><select id="documentsFilter"><option value="all">Todos los estados</option><option value="vigente" ${filter==="vigente"?"selected":""}>Vigentes</option><option value="por_vencer" ${filter==="por_vencer"?"selected":""}>Por vencer</option><option value="vencido" ${filter==="vencido"?"selected":""}>Vencidos</option><option value="sin_dato" ${filter==="sin_dato"?"selected":""}>Sin vencimiento</option></select></section><div class="table-shell"><table><thead><tr><th>Trabajador</th><th>Categoría</th><th>Documento</th><th>Realizado</th><th>Vence</th><th>Estado</th><th>Archivo</th></tr></thead><tbody id="documentsRows"></tbody></table></div>`;}
export function bindDocumentsEvents(){document.getElementById("documentsSearch")?.addEventListener("input",event=>{query=event.target.value;renderRows();});document.getElementById("documentsFilter")?.addEventListener("change",event=>{filter=event.target.value;renderRows();});renderRows();}
