import { observeWorkers, saveWorker } from "./workers-service.js";
import { observeSites } from "./sites-service.js";
import { SITE_COLORS, SHIFT_TYPES } from "./catalogs.js";
import { dayShift, baseShiftType, escapeHtml, shiftLabel, todayString } from "./worker-utils.js";
let workers=[];let sites=[];let started=false;let refresh=null;let viewDate=new Date();let lastSnapshot=null;
function fmtDate(year,month,day){return `${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;}
function daysInMonth(year,month){return new Date(year,month+1,0).getDate();}
function siteColor(name){const index=sites.findIndex(item=>item.nombre===name);return SITE_COLORS[index>=0?index%SITE_COLORS.length:0];}
function cellStyle(info){if(info.faena)return `background:${siteColor(info.faena)}`;if(info.tipo==="trabajo")return "background:#2f3944";if(info.tipo==="extra")return "background:#e2571f";if(info.tipo==="permiso")return "background:#c8342f";return "background:#e7e8e3;color:#4f565d";}
function cellLabel(info){if(info.faena)return info.faena.replace(/\s+/g,"").slice(0,3).toUpperCase();return ({trabajo:"T",descanso:"D",extra:"HE",permiso:"P"})[info.tipo]||"";}
function renderMatrix(){const root=document.getElementById("shiftMatrix");if(!root)return;const year=viewDate.getFullYear(),month=viewDate.getMonth(),days=daysInMonth(year,month);const headers=Array.from({length:days},(_,i)=>`<th>${i+1}</th>`).join("");const body=workers.map(worker=>`<tr><td class="shift-name"><strong>${escapeHtml(worker.nombre)}</strong><div class="table-sub">${escapeHtml(worker.cargo||"")}</div></td>${Array.from({length:days},(_,i)=>{const date=fmtDate(year,month,i+1),info=dayShift(worker,date);return `<td><button class="shift-cell" style="${cellStyle(info)}" data-worker="${worker.id}" data-date="${date}" title="${escapeHtml(`${shiftLabel(info.tipo)} ${info.faena||""} ${info.nota||""}`)}">${cellLabel(info)}</button></td>`;}).join("")}</tr>`).join("");root.innerHTML=`<table class="shift-table"><thead><tr><th class="shift-name">Trabajador</th>${headers}</tr></thead><tbody>${body}</tbody></table>`;root.querySelectorAll("[data-worker][data-date]").forEach(button=>button.addEventListener("click",()=>openDayModal(button.dataset.worker,button.dataset.date)));}
function openDayModal(workerId,date){const worker=workers.find(item=>item.id===workerId);if(!worker)return;const info=dayShift(worker,date);const modalRoot=document.getElementById("modalRoot");modalRoot.innerHTML=`<div class="modal-backdrop" id="shiftBackdrop"><section class="modal-card"><header class="modal-header"><div><h2>Editar día</h2><p>${escapeHtml(worker.nombre)} · ${date}</p></div><button class="modal-close" id="closeShift" type="button">✕</button></header><form id="shiftForm"><div class="modal-body"><div class="form-grid"><div class="field"><label>Estado</label><select name="tipo">${SHIFT_TYPES.map(([value,label])=>`<option value="${value}" ${info.tipo===value?"selected":""}>${label}</option>`).join("")}</select></div><div class="field"><label>Faena</label><select name="faena"><option value="">Sin faena</option>${sites.map(site=>`<option value="${escapeHtml(site.nombre)}" ${info.faena===site.nombre?"selected":""}>${escapeHtml(site.nombre)}</option>`).join("")}</select></div><div class="field span-2"><label>Nota</label><textarea name="nota" rows="3">${escapeHtml(info.nota||"")}</textarea></div></div><div class="metadata-note">Estado base del ciclo: ${shiftLabel(baseShiftType(worker,date))}. Si guardas el mismo estado base sin faena ni nota, se elimina la excepción.</div></div><footer class="modal-footer"><button class="btn btn-soft" id="cancelShift" type="button">Cancelar</button><button class="btn btn-primary" type="submit">Guardar</button></footer></form></section></div>`;const close=()=>modalRoot.innerHTML="";document.getElementById("closeShift").addEventListener("click",close);document.getElementById("cancelShift").addEventListener("click",close);document.getElementById("shiftForm").addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.currentTarget);lastSnapshot={workerId,overrides:JSON.parse(JSON.stringify(worker.overrides||{}))};const tipo=String(data.get("tipo")||"descanso"),faena=String(data.get("faena")||""),nota=String(data.get("nota")||"").trim(),base=baseShiftType(worker,date);const overrides={...(worker.overrides||{})};if(tipo===base&&!faena&&!nota)delete overrides[date];else overrides[date]={tipo,faena,nota};await saveWorker({...worker,overrides});close();});}
export function initShiftsModule(onChange){refresh=onChange;if(started)return;started=true;observeWorkers(data=>{workers=data;if(refresh)refresh();});observeSites(data=>{sites=data;if(refresh)refresh();});}
export function renderShifts(){const label=new Intl.DateTimeFormat("es-CL",{month:"long",year:"numeric"}).format(viewDate);return `<section class="module-header"><div><h2>Turnos</h2><p>Ciclo configurable y excepciones diarias por faena.</p></div><div class="header-actions"><button class="btn btn-soft" id="undoShift" ${lastSnapshot?"":"disabled"}>Deshacer</button><button class="btn btn-soft" id="previousMonth">←</button><strong class="month-label">${escapeHtml(label)}</strong><button class="btn btn-soft" id="nextMonth">→</button></div></section><div class="shift-legend"><span><i style="background:#2f3944"></i>Trabajo</span><span><i style="background:#e7e8e3"></i>Descanso</span><span><i style="background:#e2571f"></i>Hora extra</span><span><i style="background:#c8342f"></i>Permiso</span></div><div class="table-shell shift-shell" id="shiftMatrix"></div>`;}
export function bindShiftsEvents(){document.getElementById("previousMonth")?.addEventListener("click",()=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()-1,1);if(refresh)refresh();});document.getElementById("nextMonth")?.addEventListener("click",()=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()+1,1);if(refresh)refresh();});document.getElementById("undoShift")?.addEventListener("click",async()=>{if(!lastSnapshot)return;const worker=workers.find(item=>item.id===lastSnapshot.workerId);if(worker)await saveWorker({...worker,overrides:lastSnapshot.overrides});lastSnapshot=null;if(refresh)refresh();});renderMatrix();}
